# ansible/roles/testomgeving/tasks/main.yml
# Set up the VM as a test environment for Ansible roles, based on Docker and
# Molecule.
---
- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: testomgeving

- name: Ensure the necessary (apt) packages are installed
  apt:
    name: "{{ test_packages }}"
    state: present
    update_cache: true
  tags: testomgeving

- name: Ensure the Docker group exists
  group:
    name: docker
    state: present
  tags: testomgeving

- name: Ensure user Vagrant is a member of the Docker group
  user:
    name: vagrant
    groups:
      - docker
  tags: testomgeving

- name: Ensure Docker daemon metrics can be scraped by Prometheus
  template:
    src: etc_docker_daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker
  tags: testomgeving

- name: Ensure necessary services are running and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ test_services }}"
  tags: testomgeving

- name: Enable some useful aliases for managing Docker
  copy:
    src: docker-aliases.sh
    dest: /etc/profile.d/docker-aliases.sh
    owner: root
    group: root
    mode: 0644
  tags: testomgeving

- name: Create a Docker volume for persistent data
  docker_volume:
    volume_name: "{{ item }}"
    state: present
  with_items: "{{ test_volumes }}"
  tags: testomgeving

# We create a separate network for permanent containers, so the first containers
# spun up by students get the expected, default IP address. We specify the
# subnet, since we will need the IP address of the host system and we want that
# to be predictable (default: 172.30.0.1)
- name: Create a Docker internal network for permanent containers
  docker_network:
    name: mgmt_net
    ipam_config:
      - subnet: "{{ test_subnet }}"
        gateway: "{{ test_ip }}"
  tags: testomgeving

- name: Create a Docker container for Portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    state: started
    restart_policy: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    comparisons:
      networks: strict
    networks:
      - name: mgmt_net
    networks_cli_compatible: true
    network_mode: default
  tags: testomgeving
